### ISSUE TITLE
AmericanDad v.1.4.0

### ISSUE THREAD

**Issue by FPS-86** [BrSamedi/AmericanDadBot#1]
Не работает новой версии AmericanDad v.1.4.0

**Comment by BrSamedi** [comment]
Проверил. На 1.4.0 бот до сих пор работает и за еду и за билеты. Необходимо больше инфы. В какой момент перестает работать (находит окно Noxa, доходит до арены, начинает перебирать противников)? Какая версия Nox? При необходимости, можете скинуть мне скрин ошибки на почту z13s12@yandex.ru

**Comment by FPS-86** [comment]
Ответил на почту
