### ISSUE TITLE
1.9.0 update

### ISSUE THREAD

**Issue by NorbertRheon** [BrSamedi/AmericanDadBot#2]
As far as I understand, you are no longer interested in this game or you do not have free time to develop a bot. Could you still release a patch for 1.9.0 or explain how I can fix this now and in case of other changes.

**Comment by BrSamedi** [comment]
Hi, no, I'm still playing, but I rarely use a bot now. I only update when anybody asks.
I've released new version for 1.9.1. and made some upgrades. Maybe it will work more longer without a patch.

**Comment by NorbertRheon** [comment]
Thank you very much! Can I somehow contact you outside the github?

**Comment by BrSamedi** [comment]
Yep, of course
Fb: https://www.facebook.com/I3r.Samedi
E-mail: z13s12@yandex.ru
