### ISSUE TITLE
Auto not working in latest version

### ISSUE THREAD

**Issue by noobfromvn** [BrSamedi/AmericanDadBot#3]
The auto not working in latest version. It's alway show MsgBox: Not enough resources.
Could you help me fix it?

**Comment by BrSamedi** [comment]
Sorry, I don't play American Dad for a long time and I don't have NOX now.
But you can try fix it by changing parameters on lines 306,307 in AmericanDadBot.ahk:
foodCount := ReadPower(400,185,133,-10)
foodNeed := ReadPower(374,744,139,5)

//Read Power(x,y,width,height)
You have to install https://www.autohotkey.com/ and rebuild .exe with it. Also autohotkey has "window spy" to detect x,y points for ReadPower()

**Comment by noobfromvn** [comment]
Thank you! I will try to fix it!
